### PR TITLE
Enforce global namespace on is_iterable calls

### PR DESCRIPTION
**Pull request by GwendolenLynch**
Related to #32

### CODE REVIEW

**Comment by CarsonF** [comment]
I really would rather not....it looks so ugly too me...

**Comment by GwendolenLynch** [comment]
It is more performant, and it is clear the method is global when an exception occurs.

**Comment by CarsonF** [comment]
> it is clear the method is global when an exception occurs.

~An exception specifies the fully qualified name.~ Nvm I see what you mean. I still stand by my next point. 🔽 

> It is more performant

I would rather wait until we require 5.6+ and import the functions just like we import the global classes.

**Comment by GwendolenLynch** [comment]
> > it is clear the method is global when an exception occurs.

> An exception specifies the fully qualified name.

That's the thing, in the case of `is_iterable` the exception was claiming it was a method in this library.

**Comment by CarsonF** [comment]
Yep I realized that and edited my last response. Sorry for the confusion.

**Comment by GwendolenLynch** [comment]
Haha … We should've stuck to Slack

**Review by CarsonF — APPROVED** [review]

**Pull request merged**
